# Generated by Django 4.0.1 on 2022-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0002_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='Description Missing', max_length=200),
        ),
    ]
