# Generated by Django 4.0.1 on 2022-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0004_recipe_immagine_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='immagine',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
