# Generated by Django 4.0.1 on 2022-02-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0005_alter_recipe_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='immagine',
            field=models.ImageField(default=' ', upload_to=''),
        ),
    ]
